feat: completed task 39 'Password'
IT-Academy-Ruby/lessoner_project_frontend pull request #10
Opened 2022-10-03 18:10 UTC by Kurilo-Pavel

2022-10-03 20:25 UTC, Evgeniy121212 commented on src/FormInput.js
> +    </div>
don't use inline styles - use `className` and css-classes for that

2022-10-03 20:25 UTC, Evgeniy121212 commented on src/FormInput.js
> +             type={type}
`type={ isOpen ? "text" : "password" }`

where `isOpen` - value from `useState`-hook, and settled at the `showPassword`-function

2022-10-03 20:25 UTC, Evgeniy121212 commented on src/Registration.js
> +import FormInput from "./FormInput";
Please, put that file to the folder `/src/components/PasswordWithConfirm` and make it .tsx

2022-10-03 20:25 UTC, Evgeniy121212 commented on src/Registration.js
> +      </form>
1. form will be included into the another ticket
2. password "with open-close eyes" not used when used "password" and "confirm password" fields

2022-10-03 20:25 UTC, Evgeniy121212 commented on src/style/style.scss
> +}
please, remove that file:
1. it should be at the project, but into the another place
2. modal is not included into your ticket

2022-10-05 18:45 UTC, NatashaMikhaltsova requested changes

2022-10-05 18:45 UTC, NatashaMikhaltsova commented on src/components/Password.tsx
> +      {(isError && isBlur) && <span className={'error'}>Password must contain from 6 to 256 characters</span>}
store error messages in state

2022-10-05 18:45 UTC, NatashaMikhaltsova commented on src/components/Password.tsx
> +    <div className={'password'}>
apply classnames like className='password' without {}

2022-10-05 18:45 UTC, NatashaMikhaltsova commented on src/components/Password.tsx
> +  )
Should there be Confirm Password field here?

2022-10-06 10:13 UTC, OxygenO22 approved these changes

2022-10-06 12:38 UTC, Terapool requested changes

2022-10-06 15:58 UTC, Terapool approved these changes

2022-10-06 18:12 UTC, DimitarShemet approved these changes

2022-10-09 19:13 UTC, NatashaMikhaltsova commented on src/components/Password.tsx
> +  )
Discussed on daily meetings

2022-10-09 19:13 UTC, NatashaMikhaltsova approved these changes

2022-10-09 20:13 UTC, merged