Fix rating
IT-Academy-Ruby/lessoner_project_frontend pull request #110
Opened 2023-01-12 18:04 UTC by DimitarShemet

2023-01-12 18:52 UTC, Terapool requested changes

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +  isRatingFreezen: boolean;
isRatingFrozen

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +  const [hover]=useState(0);
Please, spaces: [hover] = ...

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +
const isRatingEnabled = isAuthorized && !isRatingFrozen

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +            style={isAuthorized && !isRatingFreezen? { cursor: "pointer" } : { cursor: "auto" }}
style={{cursor: isRatingEnabled ? "pointer" : "default"}}

but it is better here use className for toggling cursor

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
>        {[...Array(5)].map((star, index) => {
please, create const STARS_NUMBER = 5 and then use it ...Array(STARS_NUMBER)

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
>              className={ratingUnit <= (hover || rating) ? "on" : "off"}
use classNames library for complex logic

2023-01-12 18:52 UTC, Terapool commented on src/pages/VideoViewPage.tsx
> +  // Написат начальное значение реальное
Remove this comment, please

2023-01-12 18:52 UTC, Terapool commented on src/pages/VideoViewPage.tsx
> +};
emty line, then export default then empty line...

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +}: VideoRatingProps) => {
Please, create component RatingStar and use it in VideoRating component to render star

2023-01-12 18:52 UTC, Terapool commented on src/components/VideoRating.tsx
> +            onClick={isAuthorized && !isRatingFreezen? () => {
Too long, too many lines - please write onClick handler separately and then insert its name

2023-01-13 14:29 UTC, Terapool approved these changes

2023-01-14 13:03 UTC, valer-sky approved these changes

2023-01-17 12:32 UTC, closed without merging