Les-45-create number phone
IT-Academy-Ruby/lessoner_project_frontend pull request #13
Opened 2022-10-04 15:06 UTC by Kurilo-Pavel

2022-10-05 10:15 UTC, Terapool requested changes

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +  // const phoneNumberRegex = /[^\d]$/;
Please remove commented code.

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +      // if (phoneNumberRegex.test(e.currentTarget.value)) {
Please remove commented code.

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +      {/*{(isBlur) && <span className={'error'}>Please enter a phone number in international format</span>}*/}
Please remove commented code.

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +    <div className={'phoneNumber'}>
className="phoneNumber"

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +      <label className={'phoneNumberLabel'}>Phone number</label>
class name in simple quotes:

className="phoneNumberLabel"
className="phoneNumberInput"

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +             type={'text'}
type="text"

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +  const fieldHandler = (e: React.FormEvent<HTMLInputElement>) => {
const handleFieldChange

2022-10-05 10:15 UTC, Terapool commented on src/component/PhoneNumber.tsx
> +  const blurHandle = (e: React.FormEvent<HTMLInputElement>) => {
remove this handler as it is not used

2022-10-05 10:15 UTC, Terapool commented on src/component/phoneNumber.scss
> +.phoneNumber {
.phoneNumber {
&nbsp;&nbsp;margin: 20px 0;

&nbsp;&nbsp;&Label {
&nbsp;&nbsp;...
&nbsp;&nbsp;}
&nbsp;&nbsp;&Input {
&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;}

2022-10-05 20:25 UTC, NatashaMikhaltsova requested changes
Please rename folder with components to 'components'

2022-10-06 10:12 UTC, OxygenO22 approved these changes

2022-10-06 11:09 UTC, Terapool requested changes

2022-10-06 11:09 UTC, Terapool commented on src/component/phoneNumber.scss
> +$blue: #0747a6;
Where do you use this $blue variable?

2022-10-06 13:01 UTC, Terapool approved these changes

2022-10-06 16:35 UTC, NatashaMikhaltsova approved these changes

2022-10-06 18:12 UTC, DimitarShemet approved these changes

2022-10-08 18:29 UTC, merged