Les-42-modal-modal/page for registration
IT-Academy-Ruby/lessoner_project_frontend pull request #15
Opened 2022-10-05 13:41 UTC by Kurilo-Pavel

2022-10-05 13:53 UTC, Terapool requested changes

2022-10-05 13:53 UTC, Terapool commented on src/components/modal/Modal.tsx
> +    console.log(visible)
Please, remove console.log(visible)

2022-10-05 13:53 UTC, Terapool commented on src/components/modal/Modal.tsx
> +  const [visible, setVisible] = useState('');
1. Change naming [visible, setVisible] -> [isVisible, setIsVisible]
2. it is better to have it boolean type:

const [isVisible, setIsVisible] = useState(false)

2022-10-05 20:14 UTC, NatashaMikhaltsova requested changes
Rename folder with components from 'src/components/modal/' to 'components' and place it inside src

2022-10-06 10:11 UTC, OxygenO22 approved these changes

2022-10-06 10:31 UTC, Terapool approved these changes

2022-10-06 16:40 UTC, NatashaMikhaltsova approved these changes

2022-10-06 17:51 UTC, DimitarShemet approved these changes

2022-10-08 18:30 UTC, merged