Checkbox component
IT-Academy-Ruby/lessoner_project_frontend pull request #21
Opened 2022-10-11 17:56 UTC by OxygenO22

2022-10-11 18:19 UTC, Kurilo-Pavel approved these changes

2022-10-11 19:24 UTC, Evgeniy121212 approved these changes
Finally! :+1:

2022-10-11 20:50 UTC, valer-sky approved these changes

2022-10-11 20:57 UTC, Evgeniy121212 requested changes

2022-10-11 20:57 UTC, Evgeniy121212 commented on src/components/Checkbox.tsx
> +const Checkbox = (props) => {
props must have type

2022-10-12 07:39 UTC, OxygenO22 commented on src/components/Checkbox.tsx
> +const Checkbox = (props) => {
done

2022-10-12 12:15 UTC, Evgeniy121212 approved these changes

2022-10-12 12:49 UTC, Terapool commented on src/components/Checkbox.module.scss
> +
remove the leading empty line

2022-10-12 12:49 UTC, Terapool commented on src/components/Checkbox.tsx
> +    return (
Please, add an empty line before return

2022-10-12 13:56 UTC, merged