feat: completed ticket 38 'UserName'
IT-Academy-Ruby/lessoner_project_frontend pull request #7
Opened 2022-10-03 16:19 UTC by Kurilo-Pavel

2022-10-03 20:43 UTC, Evgeniy121212 commented on .idea/inspectionProfiles/Project_Default.xml
> +</component>
remove that file from the PR, you can include the `.idea`-folder into the `.gitignore`-file - it will be ok to put it in that PR

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/AboutUs/AboutUs.js
> +export default AboutUs;
that page not needed according to the ticket - so it's needs to be removed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/style/style.scss
> +}
file not needed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/index.js
> +);
file not needed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/Title.js
> +export default Title;
file not needed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/Button.js
> +export default Button;
file not needed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/App.js
> +export default App;
file not needed

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/FormInput.js
> +        e.target.style.borderColor = '#0747a6';
not change e.target - use hooks and `className` for that

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/FormInput.js
> +export default FormInput;
upgrade to .tsx

2022-10-03 20:43 UTC, Evgeniy121212 commented on src/FormInput.js
> +let password = null;
variable not used - it should be removed

2022-10-05 13:34 UTC, Terapool requested changes

2022-10-05 13:34 UTC, Terapool commented on src/components/UserName.tsx
> +
Remove this empty line

2022-10-05 13:34 UTC, Terapool commented on src/components/userName.scss
> +$blue: #0747a6;
$blue: #0747a6; 

where do you use this constant?

2022-10-05 20:22 UTC, NatashaMikhaltsova requested changes
Please rename folder with components to 'components'

2022-10-06 10:14 UTC, OxygenO22 approved these changes

2022-10-06 16:01 UTC, Terapool approved these changes

2022-10-06 16:33 UTC, NatashaMikhaltsova approved these changes

2022-10-08 18:31 UTC, merged