Les 417 add category
IT-Academy-Ruby/lessoner_project_frontend pull request #73
Opened 2022-12-08 14:35 UTC by Kurilo-Pavel

2022-12-11 18:14 UTC, Terapool requested changes

2022-12-11 18:14 UTC, Terapool commented on src/components/body/content/categories/CategoriesUser.tsx
> +      {allCategories.map(category => category.status === "active" ?
{allCategories.map(category => category.status === "active" && ...

without null at the end

2022-12-12 10:20 UTC, OxygenO22 approved these changes

2022-12-12 17:50 UTC, Evgeniy121212 approved these changes
approving ahead

2022-12-12 20:14 UTC, NatashaMikhaltsova approved these changes

2022-12-13 07:50 UTC, valer-sky approved these changes

2022-12-19 19:10 UTC, Terapool approved these changes

2022-12-19 19:10 UTC, merged