Les 378 create requests for lessons page
IT-Academy-Ruby/lessoner_project_frontend pull request #75
Opened 2022-12-10 10:38 UTC by DimitarShemet

2022-12-11 08:11 UTC, valer-sky approved these changes

2022-12-11 17:04 UTC, Terapool requested changes

2022-12-11 17:04 UTC, Terapool commented on src/components/body/content/lessons/LessonsHelper.tsx
> +export const getCategoryNameById = (
Rename getCategoryNameById -> GetDataWithCategoryNames

2022-12-11 17:04 UTC, Terapool commented on src/translations/en.js
> +    "This email address is already registered",
How does these translations relate to your ticket?

2022-12-11 19:25 UTC, DimitarShemet commented on src/components/body/content/Rating/Rating.tsx
> +        {props.rating} {`(${props.totalVotes})`}
Sergey, we had conversation with you about it, i did it because of type of props, now i can use right props type: number

2022-12-11 19:27 UTC, DimitarShemet commented on package.json
> +    "i": "^0.3.7",
deleted

2022-12-11 19:28 UTC, DimitarShemet commented on src/components/body/content/lessons/Lessons.tsx
> +        const dataWithCategoryname = getCategoryNameById(categories, data);
renamed

2022-12-12 10:19 UTC, OxygenO22 approved these changes

2022-12-12 10:24 UTC, Terapool approved these changes

2022-12-12 17:47 UTC, Evgeniy121212 approved these changes

2022-12-13 10:50 UTC, merged