Les 450 create connecting between FE and BE
IT-Academy-Ruby/lessoner_project_frontend pull request #78
Opened 2022-12-15 15:09 UTC by Kurilo-Pavel

2022-12-16 15:29 UTC, Evgeniy121212 approved these changes
approving ahead

2022-12-19 06:47 UTC, valer-sky approved these changes

2022-12-19 12:13 UTC, Terapool requested changes

2022-12-19 12:13 UTC, Terapool commented on src/pages/LoginPage.tsx
> +          if (!isEmail && values.email.length > 0) {
if (!isEmail && values.email.length > 0) =>

if (!isEmail && values.email.length)

2022-12-19 12:13 UTC, Terapool commented on src/pages/ResetPasswordPage.tsx
> +          if (!isEmail && isEmail!=="") {
Please, spaces over ==

2022-12-19 12:13 UTC, Terapool commented on src/translations/ru.js
> +  "app.code.errorLength": "Коде должен содержать {maxSymbol} символов. ",
Коде ?

2022-12-19 12:13 UTC, Terapool commented on src/translations/ru.js
> +  "app.YourselfPage.errorIncorrectName":"Неверное имя пользователя",
Please, spaces afer ":"

2022-12-20 11:07 UTC, Terapool approved these changes

2022-12-29 12:17 UTC, merged