Les 451 Create sign out
IT-Academy-Ruby/lessoner_project_frontend pull request #82
Opened 2022-12-19 20:00 UTC by Kurilo-Pavel

2022-12-20 11:14 UTC, Terapool requested changes

2022-12-20 11:14 UTC, Terapool commented on src/components/UserCategory.tsx
> +  // key: string;
Remove this commented line. No need in it

2022-12-20 11:14 UTC, Terapool commented on src/components/UserCategory.tsx
> +    <>
No need in the react fragment here as you have single wrapper - div

2022-12-20 11:14 UTC, Terapool commented on src/components/body/Body.tsx
> +      <Header onLanguageSwitch={onLanguageSwitch}/>
Please, insert a space before closing "/" at the end:
Header onLanguageSwitch={onLanguageSwitch} /

2022-12-20 11:14 UTC, Terapool commented on src/components/body/header/Avatar.tsx
> +  const initial = nameDecode.split(" ")
please, give more descriptive name, e.g. initialName...

2022-12-20 11:14 UTC, Terapool commented on src/components/body/header/Header.tsx
> +          {isRegister ? <Avatar
it is better 

{isRegister && ,,,,}
{!isRegister && ,,,}

instead of ternary operstor as it difficult to inspect in the code

2022-12-20 19:21 UTC, Terapool requested changes

2022-12-20 19:21 UTC, Terapool commented on src/components/body/header/Language.tsx
> +            {language === lang.code ?
language === lang.code &&. ... without null

2022-12-20 20:36 UTC, NatashaMikhaltsova approved these changes

2022-12-21 09:47 UTC, Terapool approved these changes

2022-12-21 10:42 UTC, valer-sky approved these changes

2022-12-29 10:57 UTC, Kurilo-Pavel commented
to be recreated

2022-12-29 11:02 UTC, closed without merging