Les 452 user page
IT-Academy-Ruby/lessoner_project_frontend pull request #94
Opened 2023-01-03 23:07 UTC by Kurilo-Pavel

2023-01-04 10:07 UTC, Terapool requested changes
Please, see if you really need this file: 
src/components/icons/131.jpg

2023-01-04 10:07 UTC, Terapool commented on src/components/body/header/Avatar.tsx
> +            <FormattedMessage id="app.avatar.personalData"/>
[space]/&gt;

2023-01-04 10:07 UTC, Terapool commented on src/components/body/header/Avatar.tsx
> +            <FormattedMessage id="app.avatar.logOut"/>
[space]/&gt;

2023-01-04 10:07 UTC, Terapool commented on src/components/body/header/Avatar.tsx
> +            <img src={Logout} alt="logout"/>
[space]/&gt;

2023-01-04 10:07 UTC, Terapool commented on src/pages/FirstRegistrationForm.tsx
> +    if (isRegEmail===false) {
spaces:|
(isRegEmail[space]===[space]false)

2023-01-04 10:07 UTC, Terapool commented on src/pages/LoginPage.tsx
> +
One empty line as separator is enough. No need in extra lines here...

2023-01-04 10:07 UTC, Terapool commented on src/pages/YourselfPage.tsx
> +    if (values.name.length < minSymbol && values.name.length > 0) {
simply  values.name.length without &gt; 0

2023-01-04 10:07 UTC, Terapool commented on src/store/loginName/loginSlice.ts
> +  async (token:string)=>{
spaces

2023-01-04 10:07 UTC, Terapool commented on src/store/sign_up/signUpSlice.ts
> +export default userSlice.reducer;
empty line at the file end

2023-01-04 11:56 UTC, Kurilo-Pavel commented on src/components/PasswordAndConfirm.tsx
> +  isConfirm: boolean|string;
if isConfirm = true - it component for Confirm,

2023-01-04 12:01 UTC, Kurilo-Pavel commented on src/components/body/Body.tsx
> +      <Header onLanguageSwitch={onLanguageSwitch}/>
space befor /> removed priter.

2023-01-04 12:17 UTC, Kurilo-Pavel commented on src/components/body/content/categories/CategoriesUser.tsx
> +    <SkeletonCategory key={index}/>);
it remove pritter

2023-01-05 15:20 UTC, NatashaMikhaltsova approved these changes

2023-01-05 17:03 UTC, valer-sky approved these changes

2023-01-07 18:14 UTC, Terapool approved these changes

2023-01-09 12:43 UTC, merged