fix 3 tasks
IT-Academy-Ruby/lessoner_project_frontend pull request #98
Opened 2023-01-08 19:54 UTC by DimitarShemet

Фикс 3 тасок:
1. При темном фоне убрать белые вставки возле всплывающего окна регистарции 
2. Пофиксить цвет логотипа при смене фона сайта 
3. Переделать кебаб при нажатии на иконку пользователя (при темном фоне)

2023-01-08 20:04 UTC, Terapool requested changes

2023-01-08 20:04 UTC, Terapool commented on src/components/body/footer/Footer.tsx
> +    <footer style={{ display: "flex", justifyContent: "center" }}>
use className, not styles

2023-01-09 09:04 UTC, DimitarShemet commented on src/components/body/footer/Footer.tsx
> +    <footer style={{ display: "flex", justifyContent: "center" }}>
add className for footer

2023-01-09 09:16 UTC, Terapool approved these changes

2023-01-09 09:17 UTC, Terapool commented
To be merged as quick fix

2023-01-09 09:19 UTC, merged